### ISSUE TITLE
mapview not working on Kivy 2.0.0

### ISSUE THREAD

**Issue by kushurox** [kivy-garden/mapview#44] opened 2021-01-05 11:04 UTC
**Describe the bug**
kivy garden, Map View doesn't Work on kivy version 2.0.0, I have tried it on 1.11.1 and the code worked.

**To Reproduce**
from kivy_garden.mapview import MapView, MapMarker
from kivymd.app import MDApp
from kivymd.uix.floatlayout import MDFloatLayout

class MapWidget(MDFloatLayout):
    def __init__(self):
        super(RealBoss, self).__init__()
        m = MapView(zoom=11, lat=50.6394, lon=3.057, on_map_relocated=self.func)
        self.add_widget(m)
        marker = MapMarker(lat=50.6394, lon=3.057)
        m.add_marker(marker)

    def func(self, *args):
        print(args)

class Try(MDApp):
    def build(self):
        return MapWidget()

Try().run()

**Expected behavior**
a red marker to be placed on the map

**Screenshot**
<img width="912" alt="Screenshot 2021-01-05 at 4 30 28 PM" src="https://user-images.githubusercontent.com/38589424/103638735-545ac400-4f73-11eb-9675-5a6979b89822.png">

**Console**
[INFO   ] [Logger      ] Record log in /Users/name/.kivy/logs/kivy_21-01-05_119.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/Users/name/PycharmProjects/GUI_is_Cool/venv/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 03:13:28) 
[Clang 6.0 (clang-600.0.57)]
[INFO   ] [Python      ] Interpreter at "/Users/name/PycharmProjects/GUI_is_Cool/venv/bin/python"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'2.1 INTEL-16.1.7'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) Iris(TM) Graphics 6100'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [KivyMD      ] 0.104.2.dev0, git-Unknown, 2021-01-04 (installed at "/Users/name/PycharmProjects/GUI_is_Cool/venv/lib/python3.7/site-packages/kivymd/__init__.py")
[INFO   ] [GL          ] NPOT texture support is available
[ERROR  ] [Image       ] Not found <icons/sunny.png>
[INFO   ] [Base        ] Start application main loop

**Platform (please complete the following information):**
 - OS: MacOS Big Sur, Version 1.11
 - Python version: 3.7.1

**Comment by kushurox** [comment] 2021-01-05 11:06
i have tried using source as well. Nothing appeared as well

**Comment by xdevkroom** [comment] 2021-01-06 03:08
# Maps work well use this code instead of yours: 

from kivy_garden.mapview import MapView, MapMarker
from kivymd.app import MDApp
from kivymd.uix.floatlayout import MDFloatLayout

class MapWidget(MDFloatLayout):
    def __init__(self):
        super(MapWidget,self).__init__()
        m = MapView(zoom=11, lat=50.6394, lon=3.057, on_map_relocated=self.func)
        self.add_widget(m)
        marker = MapMarker(lat=50.6394, lon=3.057)
        m.add_marker(marker)

    def func(self, *args):
        print(args)
class Try(MDApp):
    def build(self):
        return MapWidget()

Try().run()

**Comment by xdevkroom** [comment] 2021-01-06 04:28
# Now it's working well
    
    from kivy_garden.mapview import MapView, MapMarker
    from kivymd.app import MDApp
    from kivymd.uix.floatlayout import MDFloatLayout
    
    class MapWidget(MDFloatLayout):
        def __init__(self):
            super(MapWidget,self).__init__()
            m = MapView(zoom=11, lat=50.6394, lon=3.057, on_map_relocated=self.func)
            self.add_widget(m)
            marker = MapMarker(lat=50.6394, lon=3.057)
            m.add_marker(marker)
    
        def func(self, *args):
            print(args)
    class Try(MDApp):
        def build(self):
            return MapWidget()
    
    Try().run()

**Comment by kushurox** [comment] 2021-01-06 07:12
it is still same.
<img width="912" alt="Screenshot 2021-01-06 at 12 42 07 PM" src="https://user-images.githubusercontent.com/38589424/103740071-97bd3d00-501c-11eb-9d66-52604494b076.png">

**Comment by alexnaoki** [comment] 2021-01-08 03:42
I was having the same problem. I solved this by using a source ".png".

`marker = MapMarker(lat=50.6394, lon=3.057, source='newMarker.png)`

**Comment by alexnaoki** [comment] 2021-01-08 14:56
Using kivy==1.11.1, there is no problem with the marker's source. I believe there are some incompatibilities with kivy==2.0

**Comment by kushurox** [comment] 2021-01-09 17:42
yeah the problem with 1.11.1 was that the md animations werent smooth. so i had to upgrade to 2.0.0

**Comment by runette** [comment] 2021-01-21 23:07
I have the same problem and I am a little confused about the issue is closed since it seems to be a real issue

**Comment by kushurox** [comment] 2021-01-24 17:37
alright ill just keep it open until the mods close it

**Comment by Sahil-pixel** [comment] 2021-02-18 09:03
i am facing same problem

**Comment by runette** [comment] 2021-02-18 16:12
What I ended up doing is downloading the whole of mapview into my project (it is neither very big nor does it change very fast - if at all) and then solving this problem by explicitly referencing the marker icon:

```
MapMarker(lat=self.lat, lon=self.lon, source='%path_to_icons%/Marker.png'))
```

where you do, of course, replace %path_to_icons% with the place that you put the mapview icons folder!

**Comment by macdems** [comment] 2021-07-05 10:54
This issue is caused by the fact that Kivy 2.0.0 does not load the image if the default `source` value is not changed. I have created a pull request #47 resolving this.

**Comment by Ryan-Ashton** [comment] 2021-07-19 07:50
That's great. Hopefully the pull request gets approved soon.

**Closed** 2021-07-24 23:48 UTC

**Comment by HeaTTheatR** [comment] 2022-02-07 11:18
I suggest to open this issue as the problem is still not solved. I'm using `v2.1.0.dev0` and `MacOS`. Unfortunately, none of the solutions described here work.

```python
from kivy_garden.mapview import MapView, MapMarker
from kivy.app import App


class MapViewApp(App):
    def build(self):
        mapview = MapView(zoom=11, lat=48.56705, lon=39.31706)
        marker = MapMarker(lat=47.2364, lon=39.7139)
        mapview.add_marker(marker)
        return mapview


MapViewApp().run()
```
![Снимок экрана 2022-02-07 в 14 01 43](https://user-images.githubusercontent.com/16930280/152778378-583745fd-42f9-42e0-9c95-07d958a10f8d.png)
